services:
  # http://localhost:9090/activiti-app - admin@app.activiti.com/admin
  process:
    image: ${PROCESS_SERVICES_IMAGE}:${PROCESS_SERVICES_TAG}
    environment:
      ACTIVITI_DATASOURCE_USERNAME: alfresco
      ACTIVITI_DATASOURCE_PASSWORD: alfresco
      ACTIVITI_DATASOURCE_DRIVER: org.postgresql.Driver
      ACTIVITI_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      ACTIVITI_DATASOURCE_URL: 'jdbc:postgresql://postgres-aps:5432/activiti?characterEncoding=UTF-8'
      ACTIVITI_CSRF_DISABLED: 'true'
      ACTIVITI_CORS_ENABLED: 'true'
      ACTIVITI_ES_SERVER_TYPE: rest
      ACTIVITI_ES_REST_CLIENT_ADDRESS: elasticsearch
      ACTIVITI_ES_REST_CLIENT_PORT: 9200
      ACTIVITI_ES_REST_CLIENT_SCHEMA: http
      JAVA_OPTS: ' -Xms1g -Xmx2g'
    ports:
      - 9090:8080
    depends_on:
      postgres-aps:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./license/activiti.lic:/usr/local/tomcat/lib/activiti.lic:ro
      - aps-contentstore-volume:/act_data

  # http://localhost:9091/activiti-admin - admin/admin
  process-admin:
    image: ${PROCESS_SERVICES_ADMIN_IMAGE}:${PROCESS_SERVICES_ADMIN_TAG}
    environment:
      ACTIVITI_DATASOURCE_USERNAME: alfresco
      ACTIVITI_DATASOURCE_PASSWORD: alfresco
      ACTIVITI_DATASOURCE_DRIVER: org.postgresql.Driver
      ACTIVITI_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      ACTIVITI_DATASOURCE_URL: 'jdbc:postgresql://postgres-aps-admin:5432/activiti_admin?characterEncoding=UTF-8'
      ACTIVITI_ADMIN_REST_APP_HOST: "http://process"
      ACTIVITI_ADMIN_REST_APP_PORT: 8080
      JAVA_OPTS: ' -Xms512m -Xmx1g'
    ports:
      - 9091:8080
    depends_on:
      postgres-aps-admin:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_TAG}
    container_name: elasticsearch
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - aps-es-volume:/usr/share/elasticsearch/data

  postgres-aps:
    image: postgres:${POSTGRES_TAG}
    environment:
      POSTGRES_DB: activiti
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alfresco -d activiti"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - aps-db-volume:/var/lib/postgresql/data

  postgres-aps-admin:
    image: postgres:${POSTGRES_TAG}
    environment:
      POSTGRES_DB: activiti_admin
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alfresco -d activiti_admin"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - aps-admin-db-volume:/var/lib/postgresql/data

volumes:
  aps-db-volume:
  aps-admin-db-volume:
  aps-contentstore-volume:
  aps-es-volume: